### ISSUE TITLE
wait-tray-ready terminates before the tray gets ready

### ISSUE THREAD

**Issue by ngkz** [alebastr/sway-systemd#32]
In my environment, wait-sni-host fails with below error and exits with code 0(success) before the tray gets ready

```
ERROR:wait-sni-host:Failed to wait for org.kde.StatusNotifierHost: The name org.kde.StatusNotifierWatcher was not provided by any .service files
```

```
~ ❯ systemctl cat --user wait-tray-ready.service 
# /home/user/.config/systemd/user/wait-tray-ready.service
[Install]
WantedBy=sway-session.target

[Service]
ExecStart=/nix/store/g57xlkzddirqq5iq6xy15hgqkmmzs5mk-sway-systemd-0.4.0/libexec/sway-systemd/wait-sni-ready
RemainAfterExit=true
Type=oneshot

[Unit]
Before=tray.target
Description=Wait the status icon tray ready
PartOf=sway-session.target
Wants=waybar.service
 ~ ❯ systemctl status --user wait-tray-ready.service
● wait-tray-ready.service - Wait the status icon tray ready
     Loaded: loaded (/home/user/.config/systemd/user/wait-tray-ready.service; enabled; preset: enabled)
     Active: active (exited) since Tue 2024-09-17 11:04:13 JST; 1min 43s ago
    Process: 2511 ExecStart=/nix/store/g57xlkzddirqq5iq6xy15hgqkmmzs5mk-sway-systemd-0.4.0/libexec/sway-systemd/wait-sni-ready (code=exited, status=0/SUCCESS)
   Main PID: 2511 (code=exited, status=0/SUCCESS)
        CPU: 180ms

 9月 17 11:03:48 peregrine systemd[2395]: Starting Wait the status icon tray ready...
 9月 17 11:04:13 peregrine wait-sni-ready[2511]: ERROR:wait-sni-host:Failed to wait for org.kde.StatusNotifierHost: The name org.kde.StatusNotifierWatcher was not provided by any .service files
 9月 17 11:04:13 peregrine systemd[2395]: Finished Wait the status icon tray ready.
```

**Comment by alebastr** [comment]
The error means that no compatible implementation of a tray host has appeared within the set timeout.
In the case of waybar, it could mean that the bar
* wasn't started
* doesn't have a tray module configured
* got blocked waiting for the `xdg-desktop-portal.service` because of missing `XDG_CURRENT_DESKTOP` in the `systemd --user` environment
* got blocked waiting for something else

I'm also curious, what are you trying to achieve by starting the script as a service?
AFAIK, ordering dependency on a target does not propagate to the services within the target.

**Comment by ngkz** [comment]
oops, i thought `wait-tray-ready` is terminating immediately but it is exiting after 25s timeout correctly.

`exec_always systemctl restart --user kanshi` line right after `session.sh` startup in my config  was breaking wait-tray-ready and sway-session. commenting out it fixed this issue.

my apologies. closing.
